# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fyuko <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/03 17:33:57 by fyuko             #+#    #+#              #
#    Updated: 2019/09/03 17:38:12 by fyuko            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@gcc -Wall -Wextra -Werror -c ft_display_file.c
	@gcc -Wall -Wextra -Werror ft_display_file.c -o ft_display_file
clean:
	@rm -f ft_display_file.o
fclean: clean
	@rm -f ft_display_file
.PHONY: all clean fclean
